### ISSUE TITLE
Can't get documents in a given order

### ISSUE THREAD

**Issue by mdepp** [CMPUT301F19T34/MOODeration#24]
Due to the current database structure getting documents (e.g. user information) is difficult. Firebase has a way to get all documents of a collection but getting details for a subset seems to be impossible to do in one call. One way to work around this would be to just store the details somewhere else and update as needed. However then there might be issues with security. The best way is probably to set up some kind of views (with database functions?) but that might be too involved for this project.

**Comment by rkluzinski** [comment]
I think it will be best to take a look at how other apps interact with Firebase. We don't need to stick with the schema we proposed during our meeting if it turns out to be flawed.

This page contains links to some more resources:
https://firebase.google.com/docs/android/setup/#next_steps

The API reference talks about securing and validating data and may be helpful as well: https://firebase.google.com/docs/firestore

**Comment by mdepp** [comment]
Mostly fixed this by storing timestamps with the data
