### ISSUE TITLE
Consistent emoticons and colors

### ISSUE THREAD

**Issue by rkluzinski** [CMPUT301F19T34/MOODeration#5]
**US 01.02.01**

**As a** participant, **I want** consistent emoticons and colors to depict and distinguish the emotional states in any view **so that** I can easily distinguish between different emotional states.

**Comment by rkluzinski** [comment]
There should be a predefined set of moods. https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1231499

**Comment by mdepp** [comment]
The code which sets colors on the mood history screen hard-codes the colors, and actually sets them by searching for text such as "Happy" in the data being displayed. I think instead of expandableListTitle the CustomExpandableListAdapter should be taking some form of data object which has the emotional state...

**Comment by mdepp** [comment]
Also, in my map branch I added a function to get colors for each emotional state, but that might be redundant if one is defined here

**Comment by glnnrhodes** [comment]
Moved the color definitions to the color.xml resource file for consistency across the app. Named after moods; R.color.happy ...
Will look into modifying the adapter
